server:
  port: 9191
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: students
          uri: http://localhost:8080
          predicates:
            - Path=/api/**

management:
  tracing:
    sampling:
      probability: 1.0